# Generated by Django 4.2.5 on 2023-09-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
        migrations.RemoveField(
            model_name="student",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(default="abc@gmail.com", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="password1",
            field=models.CharField(default="********", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="password2",
            field=models.CharField(default="********", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default="abc", max_length=100),
        ),
    ]
