# Generated by Django 4.2.5 on 2023-09-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_student_branch_remove_student_classroom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
